baseURL = "https://mmark.nl/"
languageCode = "en-us"
title = "Mmark: powerful markdown parser"
theme = "after-dark"

[params]
  description = "Mmark version 2 markdown site"
  author = ""
  hide_author = true
  show_menu = true
  powered_by = false

[[menu.Main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.Main]]
    name = "Syntax"
    weight = 2
    identifier = "syntax"
    url = "/post/syntax"

[[menu.Main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/post/about"

[[menu.Main]]
    name = "Github"
    weight = 4
    identifier = "github"
    url = "https://github.com/mmarkdown/mmark"
