baseURL = "https://mmark.nl/"
languageCode = "en-us"
title = "Mmark: powerful markdown parser"
theme = "hugo-theme-sam"

[[params.mainMenu]]
    link = "/about"
    text = "Mmark is a powerful markdown parser"

[[params.mainMenu]]
    link = "/plan"
    text = "Plan for version 2"

[[params.mainMenu]]
    link = "/syntax"
    text = "Syntax"
