baseURL = "https://mmark.miek.nl/"
languageCode = "en-us"
title = "Mmark: powerful markdown parser"
theme = "after-dark"

[params]
  description = "Mmark version 2 markdown site"
  author = ""
  hide_author = true
  show_menu = true
  powered_by = false

[[menu.Main]]
    name = "Syntax"
    weight = 1
    identifier = "syntax"
    url = "/post/syntax"

[[menu.Main]]
    name = "Quick Start"
    weight = 2
    identifier = "started"
    url = "/post/start"

[[menu.Main]]
    name = "FAQ"
    weight = 3
    identifier = "faq"
    url = "/post/faq"

[[menu.Main]]
    name = "About"
    weight = 4
    identifier = "about"
    url = "/post/about"

[[menu.Main]]
    name = "Github"
    weight = 5
    identifier = "github"
    url = "https://github.com/mmarkdown/mmark"

[[menu.Main]]
    name = "Binaries"
    weight = 6
    identifier = "binaries"
    url = "https://github.com/mmarkdown/mmark/releases"
