name = "After Dark"
license = "WTFPL"
licenselink = "https://choosealicense.com/licenses/wtfpl/"
description = "A deceptively simple dark theme for Hugo."
homepage = "https://git.habd.as/comfusion/after-dark/"
tags = [
  "personal",
  "minimal",
  "responsive",
  "accessible",
  "dark",
  "search",
  "blog"
]
features = [
  "Quick Installer",
  "Module System",
  "Theme Variants",
  "Lazy Loading",
  "Social Engagement",
  "Search Optimization",
  "Post Images",
  "Fuzzy Search",
  "Personalization",
  "Snippets",
  "Related Content",
  "Table of Contents",
  "Modification Dating",
  "Syntax Highlighting",
  "Taxonomy Pages",
  "Error Page",
  "Post Bylines"
]
min_version = 0.44

[author]
  name = "Josh Habdas"
  homepage = "https://habd.as"
